# Generated by Django 5.1.1 on 2024-11-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=9)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
