# Generated by Django 5.0.1 on 2024-11-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0002_userreg_level_userreg_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
